### ISSUE TITLE
Add ability to change character name

### ISSUE THREAD

**Issue by webistomin** [withastro/cli-kit#13]
Hi! 👋

I'd like to be able to [change the name](https://github.com/withastro/cli-kit/blob/main/src/messages/index.ts#L51) to something relative to my project.

**Comment by chukwumaokere** [comment]
Why wouldnt you just clone the repo, change the name and build the cli tool from your clone..?

**Comment by webistomin** [comment]
> Why wouldnt you just clone the repo, change the name and build the cli tool from your clone..?

Of course, I can do it, but this approach has problems:

1. you can't copy any code because there are licenses
2. you will have to maintain the library code yourself

**Comment by natemoo-re** [comment]
Hey @webistomin—I'm glad you like Houston! 

We don't have plans to support customization in `@astrojs/cli-kit` at this time since it is intended for our own internal libraries. Obviously we've released this code under the MIT license, so you're free to copy/modify it for your own project if you include the proper attribution.
